config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :sushi_rolls

  root 'sushi_rolls#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sushi_roll.rb
class SushiRoll < ApplicationRecord
  belongs_to :user
  validates_presence_of :name, :price, :roll_count, :spicy, :fish, :wrap

  def self.by_price
    order(:price)
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates_presence_of :first_name, :last_name, :gender, :age
  validates_inclusion_of :gender, in: %w(Male Female Other)
  validates :age, numericality: {
    greater_than_or_equal_to: 5,
    less_than_or_equal_to: 100
  }
  has_many :sushi_rolls, dependent: :destroy

  def is_old_enough?
    age >= 5 ? true : false
  end

  def self.by_age
    order(:age)
  end

  def had_too_much
    self.sushi_rolls.count >= 4 ? true : false
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  def configure_permitted_parameters
  devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :age, :gender])
  end
end

app/controllers/sushi_rolls_controller.rb
class SushiRollsController < ApplicationController
  before_action :set_sushi_roll, only: [:show, :edit, :update, :destroy]

  def index
    @sushi_rolls = current_user.sushi_rolls
  end

  def show
  end

  def new
    @sushi_roll = current_user.sushi_rolls.new
  end

  def edit
  end

  def create
    @sushi_roll = current_user.sushi_rolls.new(roll_params)
    if @sushi_roll.save
      redirect_to @sushi_roll, notice: 'Roll Created'
    else
      render :new
    end
  end

  def update
    if @sushi_roll.update(roll_params)
      redirect_to @sushi_roll, notice: 'Roll updated'
    else
      render :edit
    end
  end

  def destroy
    @sushi_roll.destroy
    redirect_to sushi_rolls_url, notice: 'Roll destroyed'
  end

  private
    def set_sushi_roll
      @sushi_roll = current_user.sushi_rolls.find(params[:id])
    end

    def roll_params
      params.require(:sushi_roll).permit(
        :name,
        :price,
        :roll_count,
        :spicy,
        :fish,
        :wrap,
        :description
        )
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SushiTesting</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <nav>
      <div class="nav-wrapper">
        <%= link_to 'Sushi Creator', root_path %>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
          <li><%= link_to 'Edit Information', edit_user_registration_path %></li>
          <li><%= link_to 'Add Sushi Roll', new_sushi_roll_path %></li>
          <li><%= link_to 'Log Out', destroy_user_session_path %></li>
        </ul>
      </div>
    </nav>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/sushi_rolls/edit.html.erb
<div class="row">
  <%= form_for @sushi_roll do |f| %>
    <div class="col s12 m4">
      <%= f.label :name %>
      <%= f.text_field :name, autofocus: true %>
    </div>
    <div class="col s12 m4">
      <%= f.label :price %>
      <%= f.text_field :price %>
    </div>
    <div class="col s12 m4">
      <%= f.label :roll_count, 'How many individual items come in a roll?' %>
      <%= f.text_field :roll_count %>
    </div>
    <div class="col s12 m2">
      <%= f.check_box :spicy, :checked => true %>
      <%= f.label :spicy, 'Spicy? ' %>
    </div>
    <div class="col s12 m5">
      <%= f.label :fish %>
      <%= f.text_field :fish %>
    </div>
    <div class="col s12 m5">
      <%= f.label :wrap %>
      <%= f.text_field :wrap %>
    </div>
    <div class="col s12">
      <%= f.label :description, "Tell us a little about the roll" %>
      <%= f.text_area :description %>
    </div>
    <div class="col s12 m6 offset-m6">
     <%= f.submit "Add Roll", class: 'btn' %>
    </div>
  <% end %>
</div>

app/views/sushi_rolls/index.html.erb
<div class="row">
  <div class="col s12 m4">
    <h3>Welcome <%= current_user.first_name %></h3>
    <h4>You have: <%= current_user.sushi_rolls.count %> rolls of sushi.</h4>
  </div>
  <div class="col s12 m8">
    <% if current_user.sushi_rolls.any? %>
      <% @sushi_rolls.each do |sushi_roll| %>
        <div class="row">
          <div class="col s12 m4">
            <%= sushi_roll.name %>, $<%= sushi_roll.price %>
            <br>
            <% if sushi_roll.spicy? %>
              <%= "Spicy, will melt your mouth." %>
            <% else %>
              <%= "No spice, hope you like the taste of fish." %>
            <% end %>
            <br>
            <%= sushi_roll.fish %>, <%= sushi_roll.wrap %>
            <br>
            <%= sushi_roll.description %>
          </div>
          <div class="col s12 m5">
            <img src="/assets/cal.jpg" alt="" width="90%">
            <%= "This will be an uploaded picture someday" %>
          </div>
          <div class="col s12 m3">
            <%= link_to "Edit", edit_sushi_roll_path(sushi_roll) %>
            <%= link_to "Delete", sushi_roll_path(sushi_roll), method: :delete %>
          </div>
        </div>
      <% end %>
    <% else %>
      <%= "You are low on sushi rolls. You may want to reconsider your life choices and go get real food before someone forces you to eat nasty fish" %>
      <br>
      <%= link_to 'Add some rolls', new_sushi_roll_path, class: 'btn' %>
    <% end %>
  </div>
</div>

app/views/sushi_rolls/new.html.erb
<div class="row">
  <%= form_for @sushi_roll do |f| %>
    <div class="col s12 m4">
      <%= f.label :name %>
      <%= f.text_field :name, autofocus: true %>
    </div>
    <div class="col s12 m4">
      <%= f.label :price %>
      <%= f.text_field :price %>
    </div>
    <div class="col s12 m4">
      <%= f.label :roll_count, 'How many individual items come in a roll?' %>
      <%= f.text_field :roll_count %>
    </div>
    <div class="col s12 m2">
      <%= f.check_box :spicy, :checked => true %>
      <%= f.label :spicy, 'Spicy? ' %>
    </div>
    <div class="col s12 m5">
      <%= f.label :fish %>
      <%= f.text_field :fish %>
    </div>
    <div class="col s12 m5">
      <%= f.label :wrap %>
      <%= f.text_field :wrap %>
    </div>
    <div class="col s12">
      <%= f.label :description, "Tell us a little about the roll" %>
      <%= f.text_area :description %>
    </div>
    <div class="col s12 m6 offset-m6">
     <%= f.submit "Add Roll", class: 'btn' %>
    </div>
  <% end %>
</div>

app/views/sushi_rolls/show.html.erb
<h2><%= @sushi_roll.name %></h2>
<div class="row">
  <div class="col s12 m4">
    <h3>$<%= @sushi_roll.price %></h3>
    <h5>There are <%= @sushi_roll.roll_count%> pieces per roll</h5>
    <% if @sushi_roll.spicy? %>
      <h5><%= "Spicy, will melt your mouth." %></h5>
    <% else %>
      <h5><%= "No spice, hope you like the taste of fish." %></h5>
    <% end %>
    <h5>Made with <%= @sushi_roll.fish %>, and  wrapped in <%=@sushi_roll.wrap %></h5>
    <h6>What are people saying about it:</h6>
    <p>"<%= @sushi_roll.description %>"</p>
  </div>
  <div class="col s12 m8">
    <img src="/assets/cal.jpg" alt="" width="100%">
    <p>This will be replaced with user uploaded images eventually</p>
  </div>
</div>